""""" VIM CONFIGURATION """""

    "My remaps
    let mapleader=" "
    nnoremap ; :
    nnoremap : ;
    nnoremap <BS> X
    nnoremap Y y$
    map <C-c> "+y
    nnoremap <leader>q ZQ
    nnoremap <leader><leader> :set relativenumber!<CR>
    nnoremap <leader>, :set nohlsearch<CR>
    noremap <leader>y :Yazi<CR>
    noremap <A-v> :e ~/.config/vim/vimrc<CR>

    "Line down and up
    nnoremap <A-j> :m .+1<CR>
    nnoremap <A-k> :m .-2<CR>
    inoremap <A-j> <Esc>:m .+1<CR>gi
    inoremap <A-k> <Esc>:m .-2<CR>gi
    vnoremap <A-j> :m '>+1<CR>gv
    vnoremap <A-k> :m '<-2<CR>gv

    "Select all, sudo trick and numbered list
    noremap <leader>a :normal! ggV$G$<CR>
    command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
    noremap <leader>c I0gvg

    "Windows focus, rearrange and swap
    noremap <C-j> <C-w>j
    noremap <C-k> <C-w>k
    noremap <C-h> <C-w>h
    noremap <C-l> <C-w>l
    noremap <C-n> <C-w>w
    noremap <leader>r <C-w>r
    noremap <leader>l <C-w>L
    noremap <leader>h <C-w>H

    "Buffers prev, next, delete,show and new vertical split
    noremap <leader>b :bp<CR>
    noremap <leader>n :bn<CR>
    noremap <leader>x :bd<CR>
    nnoremap <leader><Tab> :buffer<Space><Tab>
    noremap <leader>v :vnew<CR>

    "Peekaboo and FZF settings
    let g:peekaboo_prefix = '"'
    let g:peekaboo_ins_prefix = '<c-e>'
    let g:fzf_vim = {}
    let g:fzf_vim.command_prefix = 'Fzf'
    set grepprg=rg\ --vimgrep\ --smart-case\ --follow
    nnoremap <A-b> :FzfBuffers<CR>
    nnoremap <A-c> :FzfChanges<CR>
    nnoremap <A-d> :FzfFiles<CR>
    nnoremap <A-s> :FzfRg<CR>
    nnoremap <A-a> :FzfLines<CR>
    nnoremap <A-l> :FzfBLines<CR>
    nnoremap <A-m> :FzfMarks<CR>
    nnoremap <A-u> :FzfJumps<CR>
    nnoremap <A-f> :FzfHistory<CR>
    nnoremap <A-.> :FzfHistory:<CR>
    nnoremap <A-,> :FzfHistory/<CR>

    "My settings
    set background=dark   
    colorscheme wildcharm
    syntax on
    filetype plugin indent on
    set autoread hidden
    set ruler number cul
    set directory=~/Public/
    set ignorecase smartcase
    set incsearch
    set laststatus=2
    set lazyredraw
    set mouse=a
    set pastetoggle=<F2>
    set scrolloff=2
    set showmatch mat=3
    set spelllang=cs,en
    set softtabstop=4 shiftwidth=4 expandtab
    set viminfo='33,<50,s10,h
    set wildcharm=<Tab>
    set wildoptions=pum,tagfile
    set undofile undolevels=5000
    set undodir=~/.config/vim/undodir
    command! -nargs=0 CleanUpUndoFiles !find ~/.vim/tmp/undo -type f -mtime +100d -delete

    "Statusline
    hi StatusLine ctermbg=0 ctermfg=92
    set statusline=%n\ %f\ %m\ \ \ %v\ \ %l/%L%<%h%w%r\ \ \ %y
    set statusline+=%=reg\ {%{v:register}}\ \ 

    "Plugins
    call plug#begin()
        Plug 'tpope/vim-commentary'
        Plug 'junegunn/vim-peekaboo'
        Plug 'chriszarate/yazi.vim'
        Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
        Plug 'junegunn/fzf.vim'
    call plug#end()

    "Cursor look
    let &t_SI = "\<Esc>[6 q" "Vertical line in INSERT
    let &t_SR = "\<Esc>[4 q" "Underline in REPLACE
    let &t_EI = "\<Esc>[2 q" "Block in other modes

    "Transparent background    
    hi Normal ctermbg=NONE
    hi NonText ctermbg=NONE
    hi LineNr ctermbg=NONE

""""" END OF FILE """""
