""""" VIM CONFIGURATION """""

"My remaps
let mapleader=" "
nnoremap ; :
nnoremap : ;
nnoremap Y y$
map <C-c> "+y
nnoremap <leader>q ZQ
nnoremap <silent><leader><leader> :set relativenumber!<CR>
nnoremap <silent><leader>, :set nohlsearch<CR>
noremap <leader>y :Yazi<CR>
noremap <silent> <A-v> :e $MYVIMRC<CR>
noremap <silent> <leader>a :normal! ggV$G$<CR> 
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

"Line down and up
nnoremap <A-j> :m .+1<CR>
nnoremap <A-k> :m .-2<CR>
vnoremap <A-j> :m '>+1<CR>gv
vnoremap <A-k> :m '<-2<CR>gv

"Window next, buffer next, delete and vsplit
noremap <leader>n <C-w>w
noremap <leader>b :bn<CR>
noremap <leader>x :bd<CR>
noremap <leader>v :vnew<CR>

"FZF settings
let g:fzf_vim = {}
let g:fzf_vim.command_prefix = 'Fzf'
set grepprg=rg\ --vimgrep\ --smart-case\ --follow
nnoremap <A-b> :FzfBuffers<CR>
nnoremap <A-c> :FzfChanges<CR>
nnoremap <A-d> :FzfFiles<CR>
nnoremap <A-g> :FzfRg<CR>
nnoremap <A-s> :FzfLines<CR>
nnoremap <A-a> :FzfBLines<CR>
nnoremap <A-m> :FzfMarks<CR>
nnoremap <A-u> :FzfJumps<CR>
nnoremap <A-f> :FzfHistory<CR>
nnoremap <A-.> :FzfHistory:<CR>
nnoremap <A-,> :FzfHistory/<CR>

"Netrw 
au FileType netrw nmap <buffer> h -
au FileType netrw nmap <buffer> <left> -
au FileType netrw nmap <buffer> l <CR>
au FileType netrw nmap <buffer> <right> <CR>
let g:netrw_banner = 0

"My settings
set background=dark   
colorscheme wildcharm
syntax on
filetype plugin indent on
set number cul autoread hidden
set ruler rulerformat=%63(%F\ \ %v\ \ \ %l/%L\ \ %p%%%=\ \%)
set shortmess+=F title
set directory=~/Public/
set ignorecase smartcase incsearch
set mouse=a scrolloff=5
set spelllang=cs,en
set softtabstop=4 shiftwidth=4 expandtab
set undofile undolevels=5000
set undodir=~/.config/vim/undodir
command! -nargs=0 CleanUpUndoFiles !find ~/.vim/tmp/undo -type f -mtime +100d -delete

"Statusline look
hi StatusLine ctermbg=0 ctermfg=22
set statusline=%n\ %f\ %m\ \ \ %v\ \ %l/%L%<%h%w%r\ \ \ %y%=\ \ 

"Cursor look
let &t_SI = "\<Esc>[1 q" "Blinking block in INSERT
let &t_SR = "\<Esc>[3 q" "Blinking underline in REPLACE
let &t_EI = "\<Esc>[2 q" "Block in other modes

"Transparent background    
hi Normal ctermbg=NONE
hi NonText ctermbg=NONE
hi LineNr ctermbg=NONE

"Plugins
call plug#begin()
    Plug 'tpope/vim-commentary'
    Plug 'chriszarate/yazi.vim'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'junegunn/vim-peekaboo'
call plug#end()

""""" END OF FILE """""
